"""update models add categ field

Revision ID: 4156b52b76b9
Revises: 44e04780cb43
Create Date: 2023-10-06 03:41:18.846341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4156b52b76b9'
down_revision = '44e04780cb43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_item_category'), 'item', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_category'), table_name='item')
    op.drop_column('item', 'category')
    # ### end Alembic commands ###
